meta_product_name: "Pocket Nurse"
meta_title: "Pocket Nurse - Health Application"
meta_description: "Reminder for medication intakes and doctors appointments"
meta_image: "Asset 2.png" # should exist in `app/assets/images/`
